const fs = require('fs');
const path = require('path');
const { marked } = require('marked');

// Configure marked options for clean styling
marked.setOptions({
  gfm: true,
  breaks: true,
});

// Helper to convert chapter titles to URL slugs
function slugify(text) {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')           // Replace spaces with -
    .replace(/[^\w\-]+/g, '')       // Remove all non-word chars
    .replace(/\-\-+/g, '-')         // Replace multiple - with single -
    .replace(/^-+/, '')             // Trim - from start of text
    .replace(/-+$/, '');            // Trim - from end of text
}

function compile() {
  const rootDir = path.join(__dirname, '..');
  const dp700Dir = path.join(rootDir, 'Dp-700');
  
  if (!fs.existsSync(dp700Dir)) {
    console.error(`Dp-700 directory not found at: ${dp700Dir}`);
    process.exit(1);
  }
  
  const domainDir = path.join(dp700Dir, 'Implement Lakehouse');
  if (!fs.existsSync(domainDir)) {
    console.error(`Domain directory not found at: ${domainDir}`);
    process.exit(1);
  }
  
  console.log(`Compiling Dp-700 resource database...`);
  
  const folders = fs.readdirSync(domainDir);
  const chapters = [];
  
  for (const folder of folders) {
    const chapterPath = path.join(domainDir, folder);
    if (!fs.statSync(chapterPath).isDirectory()) {
      continue;
    }
    
    // 1. Locate and compile Overview.md
    const mdPath = path.join(chapterPath, 'Overview.md');
    let overviewHtml = '';
    if (fs.existsSync(mdPath)) {
      const markdownContent = fs.readFileSync(mdPath, 'utf8');
      overviewHtml = marked.parse(markdownContent);
    } else {
      console.warn(`[Warning] No Overview.md found in ${folder}`);
    }
    
    // 2. Locate and parse the Question JSON file
    let questions = [];
    const files = fs.readdirSync(chapterPath);
    const jsonFile = files.find(file => file.endsWith('.json') && !file.startsWith('package'));
    
    if (jsonFile) {
      const jsonPath = path.join(chapterPath, jsonFile);
      try {
        const jsonContent = fs.readFileSync(jsonPath, 'utf8');
        const parsed = JSON.parse(jsonContent);
        questions = parsed.questions || [];
      } catch (err) {
        console.error(`[Error] Failed to parse JSON at ${jsonPath}:`, err.message);
      }
    } else {
      console.warn(`[Warning] No Question JSON file found in ${folder}`);
    }
    
    const title = folder;
    const slug = slugify(folder);
    
    chapters.push({
      id: slug,
      title: title,
      overviewHtml: overviewHtml,
      questions: questions
    });
    
    console.log(`- Compiled chapter: "${title}" (${questions.length} questions)`);
  }
  
  // Package into dynamic structured exam data
  const examData = {
    id: "dp-700",
    title: "DP-700: Implementing Data Integration Solutions with Microsoft Fabric",
    domains: [
      {
        id: "implement-lakehouse",
        title: "Implement Lakehouse",
        chapters: chapters
      }
    ]
  };
  
  // Ensure the target source folder exists
  const srcDir = path.join(rootDir, 'src');
  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir);
  }
  
  const outputPath = path.join(srcDir, 'data.js');
  const codeContent = `// Auto-generated by scripts/compile-data.js. Do not edit manually.
export const examData = ${JSON.stringify(examData, null, 2)};
`;
  
  fs.writeFileSync(outputPath, codeContent, 'utf8');
  console.log(`\nSuccessfully compiled and wrote database to ${outputPath}`);
}

compile();
